### ISSUE TITLE
readAndChangeXML.py Crashed when stop click the navigation 

### ISSUE THREAD

**Issue by xSyrix** [kahopoon/Pokemon-Go-Controller#13]
the python scripts for a while and crashed when stop navigation for a while. any idea how to fix this ?

Location Updated! latitude: -37.811419266991 longitude: 144.955592343565
Location Updated! latitude: -37.811419266991 longitude: 144.955640343565
Traceback (most recent call last):
  File "./readAndChangeXML.py", line 32, in <module>
    start()
  File "./readAndChangeXML.py", line 30, in start
    generateXML()
  File "./readAndChangeXML.py", line 17, in generateXML
    geo = getPokemonLocation()
  File "./readAndChangeXML.py", line 10, in getPokemonLocation
    response = urllib2.urlopen('http://10.0.1.155/', timeout = 1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1132, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
socket.timeout: timed out

**Comment by NazimAmin** [comment]
add a try catch in generateXML

**Comment by xSyrix** [comment]
@NazimAmin 

i am not so firmiliar with python

i add try catch like these ?

def generateXML():
    try:
    	global lastLat, lastLng
        geo = getPokemonLocation()
        if geo != None:
            if geo["lat"] != lastLat or geo["lng"] != lastLng:
                lastLat = geo["lat"]
                lastLng = geo["lng"]
                gpx = ET.Element("gpx", version="1.1", creator="Xcode")
                wpt = ET.SubElement(gpx, "wpt", lat=geo["lat"], lon=geo["lng"])
                ET.SubElement(wpt, "name").text = "PokemonLocation"
                ET.ElementTree(gpx).write("pokemonLocation.gpx")
                print "Location Updated!", "latitude:", geo["lat"], "longitude:" ,geo["lng"]
    except IOError as (errno, strerror):
    	print "I/O error({0}): {1}".format(errno, strerror)

and this is the error i get 

Traceback (most recent call last):
  File "./readAndChangeXML.py", line 35, in <module>
    start()
  File "./readAndChangeXML.py", line 33, in start
    generateXML()
  File "./readAndChangeXML.py", line 28, in generateXML
    except IOError as (errno, strerror):
ValueError: need more than 1 value to unpack

**Comment by neospio** [comment]
import socket
...
...

	except urllib2.URLError as e:
		print e.reason
	**except socket.timeout as e:
		pass**

**Comment by windse7en** [comment]
You just need to set timeout to be a larger number, I set to 100:
`response = urllib2.urlopen('http://10.0.1.155/', timeout = 100)`

**Comment by xSyrix** [comment]
thanks @windse7en it works.
