### ISSUE TITLE
Run this project on your iOS device that will actually run the Pokemon Go game

### ISSUE THREAD

**Issue by duxinxiao** [kahopoon/Pokemon-Go-Controller#16]
I can't understand what should I do.I should just run the blank single page project?In fact,I don't understand how to change the device location.

**Comment by puttichan** [comment]
Same here. :/
I just wanna know how to get started on this...
Urg...

**Comment by massimo-me** [comment]
@duxinxiao The position is changed from empty application with GPX file. The GPX file is updated continuously by python script

**Comment by ghost** [comment]
The instructions on how to "output" the GPX file are a bit obscure. Is there a command to run the `readAndChangeXML.py` after changing the IP? Running `python readAndChangeXML.py` is throwing lots of errors. 
And are we changing the IP to the IP of our own computer/device we're running the project off of?

**Comment by neospio** [comment]
Same question. How should I expect running an empty single page app which has a referencing to gpx file can initiate Pokemon Go Game?

**Comment by Hitscotty** [comment]
Well in a terminal if you have Python, just typing "python
readAndChangrXML.py" runs it and it worked pretty well for me.

**Comment by kwstasna** [comment]
@Hitscotty  i have python installed in my mac and when i run the script i get these lines

Traceback (most recent call last):
  File "/Users/kostasdev/Downloads/Pokemon-Go-Controller-master 2/readAndChangeXML.py", line 32, in <module>
    start()
  File "/Users/kostasdev/Downloads/Pokemon-Go-Controller-master 2/readAndChangeXML.py", line 30, in start
    generateXML()
  File "/Users/kostasdev/Downloads/Pokemon-Go-Controller-master 2/readAndChangeXML.py", line 17, in generateXML
    geo = getPokemonLocation()
  File "/Users/kostasdev/Downloads/Pokemon-Go-Controller-master 2/readAndChangeXML.py", line 10, in getPokemonLocation
    response = urllib2.urlopen("http://myIP/", timeout = 1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1132, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 417, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''

myIP is replaced by my actuall ip address. 

Is there any possibility to make a video of how you make it run??
Thanks!

**Comment by windse7en** [comment]
`iphone: you use to play pokemon go`
`ipad: control the movement`
The first app is installed in the ipad, it will run a webserver in iOS app to sync location.
The second blank app is installed in the iphone. After installing, you just open Pokemon Go manually. It will simulate location by the referenced gpx all the time. As it updates the lat, long, Pokemon Go will update its location.

**Comment by duxinxiao** [comment]
Thanks for help.I figure out what happen just after I ask this question.But I just have one device,so In fact I wrote a simple script to edit gpx file,and click simulate location manually.Happily it work.I think write a xcode plugin maybe better.
